New Function , updatet Readme
frozenjava/EvilPortalNano pull request #30
Opened 2019-03-24 16:32 UTC by H4xl0r

Portals are able now to send mails via the myportal.php
via calling 

`this->sendmail($sub, $bod, $sender, $email);`
where

 ```
$sub, $bod, $sender, $email is:
 subject ,body , sendermail ,recivermail.

```

2019-03-25 12:58 UTC, H4xl0r commented
@frozenjava PULL PULL PULL

2019-03-25 14:23 UTC, frozenjava commented
Thanks for the PR. I'll test it this week and merge in if no changes are required.

2019-03-25 14:39 UTC, H4xl0r commented
@frozenjava u can use this portal for testing : 
https://github.com/H4xl0r/evilportals/tree/master/portals/mailtoken

But setup smtp settings first (readme update )

2019-04-08 20:34 UTC, H4xl0r commented
still no reaction :-(

2019-04-13 00:19 UTC, frozenjava commented
I had some time to review this evening and I have a couple points of feed back:

* Technically the next version will be 3.3 not 3.1
* Although I think the portals repo maintained by you and kbeflo is cool, I don't want this project to link to them because they do host phishing content and I don't want this repo to in anyway encourage or link to phishing.

So if you can remove those things from the README that would be great and I'll review again!

2019-04-13 00:20 UTC, frozenjava commented on README.md
> +## Portal Sendmail function needs to be setup ! (optional)
Maybe add this to the wiki instead of the readme?

2019-04-13 00:20 UTC, frozenjava commented on README.md
> +### Version 3.1 (beta)
version 3.1 and 3.2 have already been release, next version is 3.3.

2019-04-13 00:21 UTC, frozenjava commented on README.md
> +Example for Portal with sendmail :
These are cool projects, but I don't want them referenced from here because they host phishing content.

2019-04-13 00:22 UTC, frozenjava requested changes
Technically the next version will be 3.3 not 3.1
    Although I think the portals repo maintained by you and kbeflo is cool, I don't want this project to link to them because they do host phishing content and I don't want this repo to in anyway encourage or link to phishing.

2019-04-13 13:47 UTC, H4xl0r commented
Will repull

2019-04-13 13:47 UTC, closed without merging